apiVersion: v1
kind: Config
current-context: admin@development                ------------------- default context that'll be used
clusters:
- name: my-kube-playground
  cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt   --- or we can provide `certificate-authority-data` with the base64 encoded crt value
    server: https://my-kube-playground:6443
- name: development (values hidden)
- name: production (hidden)

contexts:
- name: my-kube-admin@my-kube-playground
  context: 
    cluster: my-kube-playground
    user: my-kube-admin
    namespace: default
- name: admin@development
- name: dev-user@production

users:
- name: my-kube-admin
  user:
    client-certificate: /etc/kubernetes/pki/admin.crt
    client-key: /etc/kubernetes/pki/admin.key 
- name: admin
- name: dev-user